apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cluster-network-addons
metadata:
  name: kargo-cluster-network-addons
commonLabels:
  app: kargo
resources:
- network-addons/network-addons-config.yaml
- network-addons/network-addons-crd.yaml
- network-addons/network-addons-namespace.yaml
- network-addons/network-addons-operator.yaml
