apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
commonLabels:
  app: cert-manager
resources:
- cert-manager.yaml
# cluster_role.yaml
namespace: cert-manager
